services:
  db:
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public'
      EDDSA_PRIVATE_KEY: ${EDDSA_PRIVATE_KEY}
      FIRST_ADMIN_EMAIL: ${FIRST_ADMIN_EMAIL}
      FIRST_ADMIN_PASSWORD: ${FIRST_ADMIN_PASSWORD}
      NEXT_PUBLIC_EDDSA_PUBLIC_KEY: ${NEXT_PUBLIC_EDDSA_PUBLIC_KEY}
      SYNCHRONIZATION_FALLBACK_CONTACT_CATEGORY: ${SYNCHRONIZATION_FALLBACK_CONTACT_CATEGORY}
      SYNCHRONIZATION_START_DATE: ${SYNCHRONIZATION_START_DATE}
