version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.rule=Host(`lab-agora.fr`)"
      - "traefik.http.routers.app.tls.certResolver=lets-encrypt"
    networks:
      - proxy

networks:
  proxy:
    external: true
