export const PROSPECT_STATE = {
  ADDED: 'ADDED',
  CONTACTED: 'CONTACTED',
  REFUSED: 'REFUSED',
  REGISTERED: 'REGISTERED',
}

export const PROJECT_CONTRIBUTOR_STATE = {
  ASSIGNED: 'ASSIGNED',
  CONTACTED: 'CONTACTED',
  REFUSED: 'REFUSED',
  SUCCESSFUL: 'SUCCESSFUL',
  VALIDATED: 'VALIDATED',
}

export const USER_ROLE = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  MANAGER: 'MANAGER',
  MEMBER: 'MEMBER',
}

export const USER_ROLE_LABEL = {
  ADMINISTRATOR: 'Administrateur·rice',
  MANAGER: 'Chargé·e de projets',
  MEMBER: 'Membre',
}

export const USER_ROLES = Object.values(USER_ROLE)
